name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [win10-x64, osx.10.12-x64, linux-x64]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli -c Release -r ${{matrix.runtime}}
      shell: powershell
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{matrix.runtime}}
        path: ${GITHUB_WORKSPACE}/MyMediaRenamer.Cli/bin/Release/netcoreapp2.1/${{matrix.runtime}}/publish
