name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build CLI binary for Windows
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli -c Release -r win10-x64
      shell: powershell
    - name: Build CLI binary for MacOS 10.12
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli -c Release -r osx.10.12-x64
      shell: powershell
    - name: Build CLI binary for Linux
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli -c Release -r linux-x64
      shell: powershell
