name: CI

on: [push]

jobs:
  build-gui:
    name: Build GUI app
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-MSBuild@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build
      working-directory: MyMediaRenamer.Gui
      run: msbuild
  build-cli:
    name: Build CLI app
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [win10-x64, osx.10.12-x64, linux-x64]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli --self-contained -c Release -r ${{matrix.runtime}}
      shell: powershell
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{matrix.runtime}}
        path: MyMediaRenamer.Cli/bin/Release/netcoreapp2.1/${{matrix.runtime}}/publish
