name: CI

on:
  push:
    paths:
    - '*'
    - '!/docs/*'
    - '!README.md'

jobs:
  tests:
    name: Tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: dotnet test
      working-directory: MyMediaRenamer.Tests
  build-gui:
    name: Build GUI app
    needs: tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-MSBuild@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build
      working-directory: MyMediaRenamer.Gui
      run: msbuild /p:Configuration=Release
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: MyMediaRenamer.Gui
        path: MyMediaRenamer.Gui/bin/Release
  build-cli:
    name: Build CLI app
    needs: tests
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [win10-x64, osx.10.12-x64, linux-x64]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli --self-contained -c Release -r ${{matrix.runtime}}
      shell: powershell
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: MyMediaRenamer.Cli.${{matrix.runtime}}
        path: MyMediaRenamer.Cli/bin/Release/netcoreapp2.1/${{matrix.runtime}}/publish
