name: Build

on: 
- push
- workflow_dispatch

jobs:
  tests:
    name: Tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: dotnet test
      working-directory: MyMediaRenamer.Tests
  build-gui:
    name: Build GUI app
    needs: tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: microsoft/setup-msbuild@v1.1
    - uses: nuget/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
      working-directory: MyMediaRenamer.Gui
    - name: Build
      working-directory: MyMediaRenamer.Gui
      run: msbuild MyMediaRenamer.Gui.csproj /p:Configuration=Release /p:DebugType=None /p:DebugSymbols=false
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: MyMediaRenamer.Gui
        path: MyMediaRenamer.Gui/bin/Release
  build-cli:
    name: Build CLI app
    needs: tests
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [win-x64, win-arm64, osx-x64, osx.12-arm64, linux-x64, linux-arm64]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet publish ${env:GITHUB_WORKSPACE}/MyMediaRenamer.Cli/MyMediaRenamer.Cli.csproj -c Release -r ${{matrix.runtime}} /p:PublishSingleFile=true /p:PublishTrimmed=true /p:DebugType=None /p:DebugSymbols=false
      shell: powershell
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: MyMediaRenamer.Cli.${{matrix.runtime}}
        path: MyMediaRenamer.Cli/bin/Release/net6.0/${{matrix.runtime}}/publish
